### PR TITLE
[PHP7] Add ctor compat on eZContentObjectTreeNode

### PR DESCRIPTION
**Pull request by andrerom**

### CODE REVIEW

**Comment by emodric** [comment]
@andrerom Is there a specific reason we're adding this one back?

**Comment by gggeek** [comment]
To insure compat for custom code of customers?

**Comment by emodric** [comment]
@gggeek I know that :) I meant, is there some open source code out there (official or not) which breaks without it?

**Comment by andrerom** [comment]
It's for cases like this: https://github.com/ezsystems/ezfind/commit/1d2076763e5ab58fe2ba5a38b0308505a0ff88fc

So it's a bit overtime, but had a person running into it again recently since they had forgotten to upgrade ezfind.

**Pull request merged**
