### PR TITLE
Fix EZP-26172:  handle passing handlerParams by reference

### PR DESCRIPTION
**Pull request by wizhippo**
Link: https://jira.ez.no/browse/EZP-26172

### CODE REVIEW

**Comment by antoligy** [comment]
Looks good, does this potentially break BC in lower versions of PHP5?

**Comment by wizhippo** [comment]
It should't.  php5 should support the api's used.

**Comment by lolautruche** [comment]
Looks good. 

+1
Ping @andrerom @bdunogier @emodric @yannickroger

**Comment by emodric** [comment]
Needs CS fixes (whitespaces and `$re_args` variable name), but otherwise +1.

**Comment by wizhippo** [comment]
I believe I have all the CS fixed.  If not let me know,

**Comment by andrerom** [comment]
Closed by #1259

**Pull request closed without merging**
