### PR TITLE
Remove unused and deprecated/removed $HTTP_SERVER_VARS variable

### PR DESCRIPTION
**Pull request by guillaumelecerf**

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by crevillo** [comment]
+1

**Comment by tharkun** [comment]
nice +1

**Comment by andrerom** [comment]
ping @yannickroger

**Comment by yannickroger** [comment]
@andrerom Why me ? I have never used this before :)

**Comment by bdunogier** [comment]
Nobody has, Yannick :-)

**Comment by andrerom** [comment]
yep, and you have been more involved in legacy work last year, could have been @glye or @joaoinacio instead, but point is: someone needs to add last +1 *(if this also looks ok to you)* and merge ;)

**Comment by yannickroger** [comment]
+1

**Comment by yannickroger** [comment]
Thanks @guillaumelecerf

**Comment by guillaumelecerf** [comment]
Thanks ;)

**Pull request merged**
