### PR TITLE
Fixed #EZP-20165: custom tag inside custom tag

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
It is impossible to insert custom tag inside another one custom tag

https://jira.ez.no/browse/EZP-20165

### CODE REVIEW

**Comment by glye** [comment]
Does the xml schema support this?
Does eZ Platform?

**Comment by SerheyDolgushev** [comment]
@ITernovtsiy If i'm not wrong you were messing up with nested custom tags recently. Can you answer any of those questions?

**Comment by ITernovtsiy** [comment]
@SerheyDolgushev @glye Yes for both questions, there is open PR related to nested custom tags processing
https://github.com/ezsystems/ezplatform-richtext/pull/64 (waiting for @adamwojs approval)

**Comment by glye** [comment]
I'm really not competent at richtext hacking. I think if the other PR passes, we can pass this one too.
@SerheyDolgushev Does this allow custom inside custom inside custom - I mean multiple recursion levels?

**Comment by SerheyDolgushev** [comment]
@glye it should allow it. But I would double-check it, just to be sure.

**Comment by glye** [comment]
@SerheyDolgushev Could you please rebase this on 2017.12? That should ensure that the travis tests are run.

**Comment by SerheyDolgushev** [comment]
I was unable to rebase this PR because "unknow repo" source. So https://github.com/ezsystems/ezpublish-legacy/pull/1461 was submitted.

@glye Please use the new PR instead of this one.

**Pull request closed without merging**
