### PR TITLE
Fix EZP-24631: Typo in the french registration confirmation email

### PR DESCRIPTION
**Pull request by guillaumelecerf**
https://jira.ez.no/browse/EZP-24631

### CODE REVIEW

**Comment by tharkun** [comment]
+1

**Comment by andrerom** [comment]
+1 ping @yannickroger

**Comment by guillaumelecerf** [comment]
@andrerom: issue created

**Comment by andrerom** [comment]
Thanks @guillaumelecerf! Merging :)

**Comment by guillaumelecerf** [comment]
Thanks.

**Comment by yannickroger** [comment]
+1 
Glad to see that @andrerom can even review french translation PR :)

**Pull request merged**
