### PR TITLE
Fix EZP-21686: ezinfo/copyright has extra "\" that don't allow the links...

### PR DESCRIPTION
**Pull request by glye**
... to work

Alternative solution to PR #779. Implemented with nowdoc segment rather than quoted strings. Updated year to 2015. Added mailto-link for email address.

https://jira.ez.no/browse/EZP-21686

### CODE REVIEW

**Comment by glye** [comment]
Sorry, forgot to check the links, they have rotted. Will need to find out were they are now, and push an update.

**Comment by glye** [comment]
Have fixed rotted links to licence and contact page, and updated licence name and version number.

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Pull request merged**
