### PR TITLE
EZP-27011: Solr index not updated when changing a content priority

### PR DESCRIPTION
**Pull request by andrerom**
> Issue: https://jira.ez.no/browse/EZP-27011

Edited & Tested by @vnivuahc, ref: https://github.com/netgen/ezplatformsearch/issues/11

Ready for review @emodric @yannickroger @glye

### CODE REVIEW

**Comment by emodric** [comment]
I'm not sure I understand `if ( !eZSearch::getEngine() instanceof eZSearchEngine )`, but other than that, looks good :+1:

**Comment by andrerom** [comment]
> I'm not sure I understand if ( !eZSearch::getEngine() instanceof eZSearchEngine ), but other 

@emodric It's basically skipping the reindex if search engine is the default on which does not need to update anything on index changes as it is using the storage data for search.

**Comment by emodric** [comment]
>>> It's basically skipping the reindex if search engine is the default on which does not need to update anything on index changes as it is using the storage data for search.

But doesn't `eZSearch::getEngine()` return any currently configured search engine, [judging by the code of the method](https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/ezsearch.php#L463-L467)? So if search engine from `ezplatformsearch` extension is activated, it would be returned.

**Comment by andrerom** [comment]
@emodric yes and the index call will be made, like we want to in that case.

**Comment by emodric** [comment]
> yes and the index call will be made, like we want to in that case.

Damn it, I misread the interface :) Custom search engines are not instances of `eZSearchEngine` but `ezpSearchEngine` :D

**Comment by emodric** [comment]
@andrerom Going in, then? :)

**Comment by andrerom** [comment]
It was sent for QA, there where no lables for that here but added it so it's more clear ;)

**Comment by andrerom** [comment]
PR is blocked as during testing for some reason  index does not get updated on first attempt, only second time priority is updated.

If someone could verify and shed some light on to why this might happen that would be great.

**Comment by andrerom** [comment]
Merging as reported says the fix solves the issue, QA/Support seems to have different setup.

**Pull request merged**
