### PR TITLE
Fixed Security Vulnerability Reflected XSS

### PR DESCRIPTION
**Pull request by sdaoudi**

### CODE REVIEW

**Comment by glye** [comment]
Hi @sdaoudi! First, thank you for your contribution! We'll deal with it asap. Second, please do not make public PRs or Jira issues about security issues. Please follow these steps, so that we can have the fix ready before an issue becomes publicly known, not after: https://doc.ez.no/Security

**Comment by glye** [comment]
Agreed, @andrerom?

**Comment by glye** [comment]
@sdaoudi This should be merged in the `2017.12` branch rather than master. If you rebase your commit on that branch and then update the PR to reflect it, we can merge it directly. If not, we can do it for you but then the commit will be marked as mine, not yours.

**Comment by sdaoudi** [comment]
Hi @glye,

Thanks for your reply. Yes, I can rebase commit and change branch.

**Comment by sdaoudi** [comment]
I'm so sorry, but the source branch has been removed. I had to create a new fork with a new branch. See # 1425.
Thanks.

**Comment by glye** [comment]
Thanks! Closing this old one.

**Pull request closed without merging**
