### PR TITLE
Making sure all affected PHP versions are handled

### PR DESCRIPTION
**Pull request by pkamps**

### CODE REVIEW

**Comment by yannickroger** [comment]
Could you please create a jira issue so I can merge it and backport it? (ping me once it is done)

**Comment by pkamps** [comment]
JIRA issue: https://jira.ez.no/browse/COM-19984

**Comment by pkamps** [comment]
@yannickroger ping

**Comment by SylvainGuittard** [comment]
Moved to EZP project: https://jira.ez.no/browse/EZP-27106

**Pull request merged**
