### PR TITLE
Fix EZP-25301: eZContentUpload is not providing original file name to…

### PR DESCRIPTION
**Pull request by pkamps**
… custom UploadHandler

> Fixes https://jira.ez.no/browse/EZP-25301

### CODE REVIEW

**Comment by pkamps** [comment]
Follow-up pull request based on https://github.com/ezsystems/ezpublish-legacy/pull/1226

**Comment by pkamps** [comment]
Happy new year!

Could you please merge the pull-request, thanks.

**Comment by yannickroger** [comment]
We need some reviews to merge it.
Community people using legacy can you check this out ? :)

**Comment by crevillo** [comment]
looks legit to me. +1

**Comment by glye** [comment]
Not certain about this, but shouldn't `$nameString` be processed the same way as it is on line 355-359 below?
https://github.com/ezsystems/ezpublish-legacy/pull/1228/files#diff-327547fe2613b7cb36c58ec54dd25498L355

**Comment by pkamps** [comment]
I think you can leave that logic to the custom upload handler -- that's what the comment says as well
Line 246: //The handler will be responsible for the rest of the execution.

**Comment by glye** [comment]
ok, +1

**Comment by andrerom** [comment]
+1

**Comment by paulborgermans** [comment]
+1

**Comment by peterkeung** [comment]
What's the barrier to getting this merged? It has a ticket and +1 all around!

**Comment by glye** [comment]
(I corrected the issue ID and added a link)

Looks like we can merge it. Agree @andrerom?

**Comment by andrerom** [comment]
> Looks like we can merge it. Agree @andrerom?

@glye yes, but should be backported to 5.4 so QA can test that.

**Comment by glye** [comment]
@peterkeung I'm running this through QA, and if all is well I'll merge it.

**Comment by peterkeung** [comment]
OK, thanks for the update :)

**Comment by glye** [comment]
@peterkeung @pkamps Hi again! QA wasn't able to verify the fix. Could you please check their way of testing? See the long comment from Rui Silva here:
https://jira.ez.no/browse/EZP-25301?focusedCommentId=197404&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-197404

**Comment by glye** [comment]
@pkamps @peterkeung Thanks for the patch, and for working together with QA on verifying it. Sorry about the delay!
QA approved, merging.

**Pull request merged**
