### PR TITLE
Fix EZP-25331: Specify table name for path attribute filter

### PR DESCRIPTION
**Pull request by peterkeung**
https://jira.ez.no/browse/EZP-25331

Ensures that the field name does not conflict with other tables

### CODE REVIEW

**Comment by emodric** [comment]
@peterkeung How exactly this breaks with eZ Tags? As far as I can see, eZ Tags uses table aliases (i1, i2, i3), to prevent exactly this from happening.

**Comment by peterkeung** [comment]
Table aliases don't prevent a clash on the same column name if the table (alias or not) is not specified. I don't think it's the fault of eZ Tags, though, and it should be prevented at the eZ kernel level.

**Comment by andrerom** [comment]
+1

**Comment by peterkeung** [comment]
Ping @benkmugo @alconasoftware @dougplant @pkamps @thiagocampoviana @ernestob for review

**Comment by ernestob** [comment]
***
:+1:  It looks good
***

**Comment by pkamps** [comment]
You're making the DB field name more specific by prepending the 'ezcontentobject_tree'. I cannot see how that is generating a wrong or broken SQL statement. We can be certain that this DB table is always part of the SQL query, right? 

In the same function it does exactly the same for other filter keys:

case 'node_id':
{
    $filterField = 'ezcontentobject_tree.node_id';
} break;

Again, I cannot see how it would break fetches.

+1

**Comment by crevillo** [comment]
+1. this could prevent crashes if you add your own extended filter with a table containing a path_string. it may say path_string is ambigous...

**Comment by andrerom** [comment]
> You're making the DB field name more specific by prepending the 'ezcontentobject_tree'. I cannot see how that is generating a wrong or broken SQL statement. We can be certain that this DB table is always part of the SQL query, right?

In other generic fetch helper functions there is usually a argument to specify object and node table, so in those cases it could. But I also saw it is already hardcoding it several places below so I'm fully +1

**Comment by guillaumelecerf** [comment]
+1
BTW you could probably do the same for `modified_subnode` and `depth` (see the unit test)

**Comment by guillaumelecerf** [comment]
https://github.com/ezsystems/ezpublish-legacy/commit/2d6a887dff41beddc15578d152505901dbcb2eb3

**Comment by peterkeung** [comment]
+1 to that more complete version

**Comment by guillaumelecerf** [comment]
See https://github.com/ezsystems/ezpublish-legacy/pull/1238

**Comment by yannickroger** [comment]
Closed in favor of #1238

**Pull request closed without merging**
