### PR TITLE
EZP-24702: Allow Setup Wizard to work non interactively with kickstart data

### PR DESCRIPTION
**Pull request by andrerom**
https://jira.ez.no/browse/EZP-24702

Needed for @vidarl's work on ezpublish-docker project to simplify it down to just use the code as is and not workaround issues.

### CODE REVIEW

**Comment by andrerom** [comment]
review ping @crevillo @vidarl @glye

**Comment by crevillo** [comment]
I don't remember what was the problem here. Patch looks good Anyway. I'll let the others review here. +0.7 on my side.

**Comment by vidarl** [comment]
The patch makes it possible to set "continue=true" for the welcome page.
Without it, the user has to click "Next" on the welcome page before the kickstart.ini file "kicks in"....

**Comment by glye** [comment]
+1

**Comment by andrerom** [comment]
@vidarl Give me heads up for when I can merge this (given it will cause conflicts for the patch you use for this).

**Comment by andrerom** [comment]
@vidarl merging.

**Pull request merged**
