### PR TITLE
EZP-27101 : removing recursionProtect after fetching all metaData of …

### PR DESCRIPTION
**Pull request by flovntp**
…a relationList

This solve issue https://jira.ez.no/browse/EZP-27101

### CODE REVIEW

**Comment by flovntp** [comment]
my fix remove $GLOBALS["ez_content_object_recursion_protect"] after looping on all contents of a relationList.
Like this, we still avoid adding twice metadata of the same relationList but allow getting metadata in another relationList for the same content.

**Comment by pkamps** [comment]
Side note: the recursion protection is avoiding infinite loops. For example, if you edit a content object and then select exactly this content object in a objectrelationlist attribute.

I'm able to reproduce the issue. It's maybe a bit of an unusual use case (2 object relation attributes both pointing to the same related object) - but it's definitely a bug.

**Comment by pkamps** [comment]
There is a problem with this pull request: it is possible to end up in an infinite execution loop.
Here the steps to reproduce the issue:
- Create a class with 2 objectrelationlist attributes
- Create an instance (object) of this class
- Edit the instance and add object relations to both attributes. For both attributes select the content object you currently edit.
- Hit 'Send for publishing'

**Comment by natanael89** [comment]
No longer needed because of https://github.com/ezsystems/ezpublish-legacy/pull/1372

**Pull request closed without merging**
