### PR TITLE
EZP-20547: Allow specifying max. connect timeout for link check

### PR DESCRIPTION
**Pull request by joaoinacio**
This implements JIRA https://jira.ez.no/browse/EZP-20547, also resolves https://jira.ez.no/browse/EZP-24738

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by pedroresende** [comment]
+1

**Comment by yannickroger** [comment]
+1 but I would keep `2` for a perfect BC

**Comment by andrerom** [comment]
No, do 3. If the value is to low, it is to low :)

**Pull request merged**
