### PR TITLE
EZP-24289: Priority of children lost when using CLI script ezsubtreecopy.php

### PR DESCRIPTION
**Pull request by mr-wildcard**
https://jira.ez.no/browse/EZP-24289

Entirely based on schroeder's 67d95d71c0af9da20113598e3c0b0f5b5333da23 fix.

### CODE REVIEW

**Comment by yannickroger** [comment]
Thanks for the PR, can you create an issue on https://jira.ez.no for it including steps to reproduce.

+1 with an issue and the commit message updated with the issue number.

**Comment by mr-wildcard** [comment]
Thank you @yannickroger 

I'd like to, but who I should contact in order to create an account on JIRA ?

**Comment by crevillo** [comment]
hi @mr-wildcard , if you haven't already done, you can create a new one from share.ez.no in the register section. then you'll be able to login into jira with that account too.

**Comment by mr-wildcard** [comment]
Thank you @crevillo 

JIRA issue created + PR updated :)

**Comment by yannickroger** [comment]
@mr-wildcard Can you also update the commit message with something like: `Fix EZP-24289: Keep nodes priority while running ezsubtreecopy.php"
Feel free to ping me if you need some help with git to do it or when it is ready.

**Comment by mr-wildcard** [comment]
@yannickroger : I changed commit title :)

**Comment by yannickroger** [comment]
I also created an issue to make it more clear "how to create a new account" on jira, thanks for the feedback :)

**Comment by yannickroger** [comment]
Anyone else for a second +1 ?

**Comment by crevillo** [comment]
i guess it's ok, but the whole code (not the patch added by @mr-wildcard) is difficult to read and to understand. it's old :). 
Anyway, it this fix the priority thing, it wil also fix the is_invisible or is_hidden thing? i mean, if before this patch we weren't doing the ```$newNode->store()``` those others attributes were stored properly in the database?

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
Thanks @mr-wildcard

**Pull request merged**
