### PR TITLE
Fix EZP-25331: Specify table name for some more filters

### PR DESCRIPTION
**Pull request by guillaumelecerf**
https://jira.ez.no/browse/EZP-25331

Ensures that the field name does not conflict with other tables

Replaces https://github.com/ezsystems/ezpublish-legacy/pull/1229

### CODE REVIEW

**Comment by pkamps** [comment]
+1

**Comment by crevillo** [comment]
+1

**Comment by peterkeung** [comment]
+1

**Comment by yannickroger** [comment]
+1
ping @andrerom backport to 5.4 ?

**Comment by andrerom** [comment]
+1 *(and yes to backport)*

**Comment by yannickroger** [comment]
Thanks @guillaumelecerf

**Comment by guillaumelecerf** [comment]
Thanks.

**Pull request merged**
