### PR TITLE
Fix EZP-24733: Do not show Register link if user/register is disabled

### PR DESCRIPTION
**Pull request by peterkeung**
Link: https://jira.ez.no/browse/EZP-24733

It is confusing to show the Register link if user/register is disabled.

### CODE REVIEW

**Comment by peterkeung** [comment]
This is still very much needed in eZ Publish 5.4.4 and the PR is still valid.

Ping @pkamps @dougplant @bgamrat @benkmugo @thiagocamposviana @alconasoftware @ernestob

**Comment by thiagocamposviana** [comment]
Seems like a very small and valid change, I vote +1

**Comment by andrerom** [comment]
+1, ping @yannickroger

**Comment by yannickroger** [comment]
+1, let's merge it and backport it to 5.4
Thanks @peterkeung

**Comment by yannickroger** [comment]
oh, one last thing @peterkeung could you create an issue for it and add the issue number in the commit and then ping me ?
I need it for the changelog (and backport).

**Comment by peterkeung** [comment]
@yannickroger done: https://jira.ez.no/browse/EZP-24733

**Comment by yannickroger** [comment]
Thanks @peterkeung

**Pull request merged**
