### PR TITLE
Fix EZP-24754: PHP Notice while erasing content

### PR DESCRIPTION
**Pull request by pedroresende**
While erasing content in some cases PHP message: PHP Notice: Undefined offset: 0 in ezpublish_legacy/kernel/content/ezcontentoperationcollection.php

While removing content, in some strange cases it raises the exception

Link: https://jira.ez.no/browse/EZP-24754

### CODE REVIEW

**Comment by joaoinacio** [comment]
+1, looks safe :)

**Comment by pedroresende** [comment]
@yannickroger ping

**Comment by andrerom** [comment]
besides PR title being too long: +1

**Comment by yannickroger** [comment]
+1

**Comment by yannickroger** [comment]
@andrerom backport to 5.4 ?

**Comment by andrerom** [comment]
Y, and cleanup issue/or name

**Pull request closed without merging**
