### PR TITLE
EZP-28706: Fixed hardcoded PostgreSQL sequence names

### PR DESCRIPTION
**Pull request by alongosz**
**JIRA issue**: https://jira.ez.no/browse/EZP-28706

With the release of ezpublish-kernel 7.0 there comes a change to PostgreSQL sequence naming.
If we combine eZ Platform v2, Kernel 7.0 and LegacyBridge we encounter a case when Legacy code still uses old naming convention, while updated database has new sequence names (for upgrade script see ezsystems/ezpublish-kernel#2216).

See also [this commit diff discussion](https://github.com/ezsystems/ezpublish-kernel/commit/2bda94087aa902e45b6cc3edde8e1870bde284e1#commitcomment-26623682).

~This PR introduces one possible way to fix it, however not an ideal one as it performs an extra fetch (not to mention spaghetti code implementing it ;) ).
Note that I'm not changing `correctSequenceValues` method on purpose. This is used by Legacy installer which has separate schema definition, so it would require changing entire schema. The real use case exists IMHO only for existing installations.~

I tried to use for this `pg_get_serial_sequence` stored function, but as name suggests works only for SERIAL type, not any table/column bound to nextval of sequence.

Other possible solutions:
- ~Optimize code to generate statement and inject it into `SELECT currval( ... )` instead of pre-fetching.~
- Release new version of `ezpublish-legacy` which is aligned with new naming convention and any other BC breaks introduced by 7.0 (seems actually most sane to me).
- ~introduce configuration option to set sequence name pattern (could be tricky).~

Reverting sequence names to old names in Kernel 7.0 blocks implementation of unified installer using Doctrine Schema tool, as its API translates `autoincrement` to `SERIAL` data type and `table_column_seq` sequence name.

POV ping @andrerom @emodric @wizhippo 

**TODO**:
- [x] Decide which solution to choose.
- [x] Discover if there are other places that need change, taking into the account above notes.
- [x] Implement solution with extra fetch
- [x] Depends on https://github.com/ezsystems/ezpublish-kernel/pull/2216

### CODE REVIEW

**Comment by andrerom** [comment]
wdyt @wizhippo?

**Comment by wizhippo** [comment]
I like the idea of bumping version better but this would be fine too.

**Comment by emodric** [comment]
Hm... Not so sure how I feel about it. The whole point of the new releases to legacy was to make it easier for people to migrate to eZ 6, didn't it?

As for the patch itself, I can't comment on it, as I'm not really familiar with PostgreSQL, but if it works in both kernel v6 and v7, I'd keep it.

**Comment by andrerom** [comment]
Ok, so we stick with this for now in legacy then, we can always adjust later once 6.x is not relevant anymore _(Given how many are already trying to upgrade or talking/wondering about it, that is not to far off)_.

**Comment by alongosz** [comment]
Ok, closing due to last comment (I must have lost it in the stream of notifications some time ago ;) )

**Comment by andrerom** [comment]
> Ok, closing due to last comment (I must have lost it in the stream of notifications some time ago ;) )

So that means we go for new 2018.03 release then with conflicts with pre kernel 7.0, with the following:
> Release new version of ezpublish-legacy which is aligned with new naming convention and any other BC breaks introduced by 7.0 (seems actually most sane to me).

**Comment by wizhippo** [comment]
Any update on this?  I have an older installation using pgsql and would like to get it on to the current ez platfrom.

**Comment by wizhippo** [comment]
@andrerom will we be merging this in some form soon?

**Comment by andrerom** [comment]
Sorry, been off. yes we can do this I think.
1. Can you review and approve?
2. @alongosz We do the kernel PR for 2.2?  If so we can bump kernel conflict for it in this PR and aim for 2.2 + 2018.06 release.

**Comment by emodric** [comment]
@andrerom As far as I understood, this is a breaking change with previous versions of eZ Publish Legacy and whatever kernel version introduces this change, right? Should eZ kernel also have a conflict section with older versions of eZ legacy?

**Comment by andrerom** [comment]
@alongosz I guess this is ready, only missing thing is bump in conflict version right?

**Comment by alongosz** [comment]
Since we're releasing 2018.06 conflicting with previous versions of Kernel it should be relatively safe to update all references to old sequence names with the convention used by SERIAL type.

I've updated PR, let's see if Travis agrees...

**Pull request merged**
