### PR TITLE
Fix EZP-25856: Silent deprecation errors in ezpublish-legacy

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-25856

Makes use of PHP 7 less noisy :wink:

### CODE REVIEW

**Comment by lolautruche** [comment]
Ping @andrerom @bdunogier @yannickroger

**Comment by lolautruche** [comment]
Travis failure doesn't seem to be related to my change.

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Pull request merged**
