### PR TITLE
Fix EZP-24591: Add quotes in index_cluster ETag value 

### PR DESCRIPTION
**Pull request by Opencontent**
https://jira.ez.no/browse/EZP-24591

### CODE REVIEW

**Comment by yannickroger** [comment]
You should add the issue number in the commit message and maybe not link to strack overflow as everything is explained in the jira link.
"Fix EZP-24591: Add quotes in index_cluster ETag value"

**Comment by yannickroger** [comment]
+1

**Comment by Opencontent** [comment]
Its'ok now?

**Comment by andrerom** [comment]
almost, use rebase to avoid getting merge commits.

when on the branch, and you want to change your commits either with additions or just rename them
```bash
git rebase -i master
```

**Comment by Opencontent** [comment]
:( I'm lost... sorry... I go to study the git documentation

**Comment by Opencontent** [comment]
Sorry.. see https://github.com/ezsystems/ezpublish-legacy/pull/1185

**Pull request closed without merging**
