### PR TITLE
EZP-29210: Fix admin UI anchor link scroll bug

### PR DESCRIPTION
**Pull request by benkmugo**
- fixed height on the width controller element causes the user to get
'stuck' and unable to scroll back to the top when clicking on a link
targeting an in page anchor

The bug is also noted in this Jira ticket:
https://jira.ez.no/browse/EZP-29210

### CODE REVIEW

**Comment by benkmugo** [comment]
This new PR fixes the original issue and addresses the side-effect found on PR #1364 (closed)

**Comment by emodric** [comment]
I've reproduced the issue, so if this fixes it, I'm +1. I do however worry about 3rd party extensions that might use `<div id="widthcontrol-handler">` in their own left menu implementations. What happens where there are two such elements on the page, one from the extension and one from pagelayout?

**Comment by konradoboza** [comment]
This fix works (checked on Chrome, Firefox and Safari). However, is there any reason why `web/design/admin/templates/parts/user/menu.tpl` wasn't also taken into account?

**Comment by benkmugo** [comment]
@emodric the instance I was testing this on had the eZ Tags extension installed, which also has a menu include with the widthcontrol-handler in it. When there were multiple widthcontrol-handler elements in place (one from the pagelayout, one from the menu include) only the first one from the pagelayout was shown and active.
The others remained hidden/inactive. You can double-check, by adding back that element in one of the menu template includes to verify.

@konradoboza it looks like I missed that one. I'll check and update the commit shortly.

Thanks all for the quick feedback.

**Comment by benkmugo** [comment]
The update has been applied to the user template as well now, as pointed out by @konradoboza above.

**Pull request merged**
