### PR TITLE
Fix EZP-24113: eZ REST API v1: all eZ log files except error.log are disabled unless DebugOutput=enabled

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24113

Ensures AlwaysLog is honored.
Note that eZDebug error handling needs to be changed in order for logs to be written.

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger @glye @pspanja

**Comment by glye** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by gggeek** [comment]
seems legit

**Pull request merged**
