### PR TITLE
Fix EZP-24030: Relationlist contains wrong content after content removal

### PR DESCRIPTION
**Pull request by glye**
Update the attribute object relations xml whenever the main node id of an object changes. Always set it to main node id.

https://jira.ez.no/browse/EZP-24030

### CODE REVIEW

**Comment by andrerom** [comment]
Be aware that some time ago doc was updated to reflect that these kind of properties are only updated on re publish of the origin object.

some mentions of this at least here, might also be other places:
https://doc.ez.no/eZ-Publish/Technical-manual/4.x/Reference/Datatypes/Object-relations

**Comment by glye** [comment]
@andrerom Right. But this particular inconsistency is not fixed on republishing.

**Comment by andrerom** [comment]
hmm, that is something else.

**Comment by glye** [comment]
Well, in this case the bug is not triggered by modifying the relation, but rater by switching main node. So we can refer to "at the time when the relation was modified" in the doc, close as invalid, and give the patch to the original reporter as a custom workaround, if they really must have it.

**Comment by andrerom** [comment]
ok

**Pull request closed without merging**
